# Generated by Django 2.2.16 on 2021-12-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('date_created', models.DateField(auto_now=True)),
                ('date_modified', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='music')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('date_created', models.DateField(auto_now=True)),
                ('date_modified', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='video')),
            ],
        ),
    ]
